# Generated by Django 3.0.1 on 2022-11-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_suscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
