# Generated by Django 3.0.1 on 2022-11-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_suscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
