# Generated by Django 3.0.1 on 2022-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('clase', models.IntegerField()),
                ('informacion', models.CharField(max_length=40)),
            ],
        ),
    ]
